# Generated by Django 5.0.6 on 2024-05-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='contact_no',
            field=models.CharField(max_length=11),
        ),
    ]
